name: zenlearn
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^9.0.0
  camera: ^0.11.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_info_plus: ^11.3.0
  equatable: ^2.0.7
  file_picker: ^10.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_drawing_board: ^0.9.8
  flutter_local_notifications: ^15.1.3
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.4.0+1
  flutter_svg: ^2.0.9
  flutter_tesseract_ocr: ^0.4.26
  flutter_timezone: ^4.1.1
  get_it: ^8.0.3
  go_router: ^15.1.2
  image_picker: ^1.1.2
  injectable: ^2.5.0
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  lottie: ^3.3.1
  markdown: ^7.3.0
  path_provider: ^2.1.5
  pdf_render: ^1.4.12
  permission_handler: ^12.0.0+1
  saver_gallery: ^4.0.1
  screen_brightness: ^2.1.3
  screenshot: ^3.0.0
  shared_preferences: ^2.5.3
  rxdart: ^0.27.7
  timezone: ^0.9.4
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  flutter_colorpicker:
  video_player: ^2.9.5
  volume_controller: ^3.3.3
  wakelock_plus: ^1.3.2
  workmanager: ^0.5.2
  youtube_explode_dart: ^2.4.0

dev_dependencies:
  analyzer: ^5.13.0
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.0
  isar_generator: ^3.1.0+1
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/videos/
    - assets/fonts/
    - assets/pdf/
    - assets/json/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
